name: merge

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout files
      uses: actions/checkout@v3

    - name: Lint sources
      uses: jokoho48/sqflint@master
      with:
        args: --exit e --directory addons
